server:
  port: 8080

spring:
  application:
    name: airline-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/airline
    username: microgt
    password: Microgt1
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  devtools:
    livereload:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

user-service:
  service-name: user-service