server:
  port: 5551

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/eaproject?serverTimezone=UTC
    username: root
    password: 
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  devtools:
    livereload:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

user-service:
  token-secret: 123456