server:
  port: 6001

spring:
  application:
    name: geteway-service
  cloud:
    gateway:
      routes:
        - id: user-service-admin
          uri: lb://user-service
          predicates:
            - Path=/user/admin/**
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}
            - Auth=admin
        - id: user-service-edit
          uri: lb://user-service
          predicates:
            - Path=/user/edit
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}
            - Auth=passenger
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}
        - id: airline-service
          uri: lb://airline-service
          predicates:
            - Path=/airline/admin/**
          filters:
            - RewritePath=/airline/(?<segment>.*), /$\{segment}
            - Auth=admin
        - id: airline-service
          uri: lb://airline-service
          predicates:
            - Path=/airline/passenger/**
          filters:
            - RewritePath=/airline/(?<segment>.*), /$\{segment}
            - Auth=passenger
        - id: airline-service
          uri: lb://airline-service
          predicates:
            - Path=/airline/agent/**
          filters:
            - RewritePath=/airline/(?<segment>.*), /$\{segment}
            - Auth=agent
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
