server:
  port: 5552

spring:
  application:
    name: website
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  mvc:
    static-path-pattern: /static/**
    view:
      suffix: .html
  devtools:
    livereload:
      enabled: true