spring:
  application:
    name: email-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: email-sending
      auto-offset-reset: latest
      enable-auto-commit: true
      auto-commit-interval: 100
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            value:
              default:
                type: edu.miu.ea.contracts.email.Email
            trusted:
              packages: edu.miu.ea.contracts.email
    producer:
      retries: 0
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            add:
              type:
                headers: false
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
email-service:
  message-queue:
    name: ea
